apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  labels:
spec:
  selector:
    matchLabels:
      app: civoappsvc
  namespaceSelector:
    any: true
  endpoints:
    - port: http